### PR TITLE
Replaced Godeps with glide

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Thanks for the PR and hello again! :-)

I'll just xref my comment from `docker2aci`: https://github.com/appc/docker2aci/pull/174#issuecomment-225877399

Do you mind using glide here?

**Comment by tboerger** [comment]
@s-urbaniak so I have integrated glide like on the other projects and on top of that I have also added a similar build script. Fine?

**Comment by tboerger** [comment]
Now the commits are nicely separated as well.

**Comment by s-urbaniak** [comment]
@tboerger great, thanks and LGTM :-) :+1:

**Comment by jonboulle** [comment]
Do you think you could run [glide vc](https://github.com/sgotti/glide-vc) against this? Seems like a lot of cruft we don't need.

**Comment by tboerger** [comment]
Sure, I can give it a try

**Comment by tboerger** [comment]
> Do you think you could run glide vc against this? Seems like a lot of cruft we don't need.

I have used glide-vc now, but there are still a lot of changes because of the vendoring.

**Comment by tboerger** [comment]
I have updated the commit messages like on the other pull requests.

**Comment by tboerger** [comment]
@s-urbaniak @jonboulle what should we do here? There are a lot of additions because it didn't had vendoring or Godeps before. Fine for merge?

**Pull request closed without merging**
